const MAKE_CALL = 'MAKE_CALL'
const DISCONNECT_CALL = 'DISCONNECT_CALL'
const MULTPLE_INCOMING = 'MULTPLE_INCOMING'
const INCOMING_CALL = 'INCOMING_CALL'
const TWILIO_TOKEN_SUCCESS = 'TWILIO_TOKEN_SUCCESS'
const TWILIO_TOKEN_FAILURE = 'TWILIO_TOKEN_FAILURE'
const SOCKET_CONNECTION_SUCCESS = 'SOCKET_CONNECTION_SUCCESS'
const SOCKET_CONNECTION_FAILURE = 'SOCKET_CONNECTION_FAILURE'
const GET_TWILIO_TOKEN = 'GET_TWILIO_TOKEN'
const CONNECT_SOCKET = 'CONNECT_SOCKET'
const CANCEL_CALL = 'CANCEL_CALL'

export {
    MAKE_CALL,
    DISCONNECT_CALL,
    MULTPLE_INCOMING,
    INCOMING_CALL,
    TWILIO_TOKEN_SUCCESS,
    TWILIO_TOKEN_FAILURE,
    SOCKET_CONNECTION_SUCCESS,
    SOCKET_CONNECTION_FAILURE,
    GET_TWILIO_TOKEN,
    CONNECT_SOCKET,
    CANCEL_CALL,
}